### ISSUE TITLE
現状でのスケジュール(5月)

### ISSUE THREAD

**Issue by temochiz-lab** [temochiz-lab/orikasa-2022#1]
ざっくり月単位で、提出までのスケジュールを教えてください。

**Comment by Orikasa-TOKIWA** [comment]
○5月～6月前半
　・予備調査（必要そうであれば質問紙を作成する） 
　・卒業論文の文章の作成（問題・目的・方法部分）
○6月後半
　・予備調査の分析
　・本調査の準備 （ここで質問紙を作成する）
○7月～8月
　・本調査
○8～9月
　・分析
○10～11月
　・結果
　・考察 
○12月
　・仮提出
○1月
　・本提出

☆5月30日現在は，主に予備調査の準備をしています。

**Comment by Orikasa-TOKIWA** [comment]
お世話になっております。追記です。
予備調査の内容についてですが，本日のゼミ時間に渡辺先生と相談し，本調査とまとめて質問を行うことにしました。（なので予備調査は行いません。）

本調査の質問項目は現在作成中です。
6月前半には質問内容を確定させる予定です。
完成次第送らせていただきます。
よろしくお願いいたします。

**Comment by temochiz-lab** [comment]
了解しました。　チケットクローズします。
