### ISSUE TITLE
質問紙　進捗状況

### ISSUE THREAD

**Issue by Orikasa-TOKIWA** [temochiz-lab/orikasa-2022#4]
お世話になっております。折笠です。
質問紙の項目ですが，以下のGoogle Formのようにしようと考えています。
（まだ変更するかもしれないため，確定ではありませんが，参考程度に送らせていただきます。）
よろしくお願いいたします。

[折笠　卒業論文　質問紙（案） - Google フォーム.pdf](https://github.com/temochiz-lab/orikasa-2022/files/8888469/-.Google.pdf)

**Comment by temochiz-lab** [comment]
内容確認しました。
実験内容が確定していればプログラム化するのに問題のない内容です。

1点だけ、
4,6,7,8,10
のような、複数の質問がある場合、1つずつ個別に画面表示して回答するのと、
一度に全部の質問を表示して回答するのは、どちらが望ましいでしょうか？

**Comment by Orikasa-TOKIWA** [comment]
返答が遅くなってしまい申し訳ございませんでした。
ご確認いただきありがとうございます。

複数の質問がある項目ですが，1つずつ提示すると，いつ質問が終わるのかが読めず，回答者に負担がかかってしまうことが予想されるため，一度に多くの質問を表示して回答できれば良いなと考えております。

言葉で説明することが難しい部分もあったため，何となくですが私が考えている質問紙のイメージを作成してみました。
お時間があるときに見ていただけたら幸いです。お忙しいところすみません。よろしくお願いいたします
[卒論　質問紙のイメージ（折笠）0615.pptx](https://github.com/temochiz-lab/orikasa-2022/files/8907055/0615.pptx)
。

**Comment by temochiz-lab** [comment]
動作イメージ了解しました。
jsPsychの機能的に完全再現は難しそうなのですが、どこまで近づけられるか試作してみます。
(6/20週に、一旦連絡します。)

**Comment by Orikasa-TOKIWA** [comment]
ありがとうございます。
よろしくお願いいたします。

**Comment by temochiz-lab** [comment]
試作した分については、以前の授業で紹介した手順で動作確認できます。
このチケットは一旦クローズします。
